spring:
  datasource:
    url: jdbc:h2:file:./data/otp_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;LOCK_TIMEOUT=10000
    username: otp_app
    password: otp_app
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          audiences:
            - downstream-client
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0

otel:
  sdk:
    disabled: true