spring:
  datasource:
    url: jdbc:h2:file:./data/otpdb
    username: otpuser
    password: otpuser
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.zalando.logbook: TRACE

