spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otp_db?currentSchema=otp_user
    password: otp_apps
    username: otp_apps
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          audiences: downstream-client
logging:
  level:
    org.zalando.logbook: TRACE
    com.github.fabiankevin: DEBUG
    com.fabiankevin: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG

otel:
  sdk:
    disabled: true