server:
  port: 8080

spring:
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    # --- Additional JavaMail Properties ---
    properties:
      mail:
        smtp:
          # Enable SMTP authentication
          auth: true
          # Enable STARTTLS encryption (required for port 587 with many providers like Gmail)
          starttls:
            enable: true
            required: true

otp:
  expiration-minutes: 5
  max-attempts: 3
  code-length: 6

logging:
  level:
    com.fabiankevin.app: INFO