spring:
  datasource:
    url: jdbc:h2:file:./data/otp-db
    username: otpuser
    password: otpuser
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.zalando.logbook: TRACE
    com.github.fabiankevin: DEBUG

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0

otel:
  sdk:
    disabled: true