server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  model-converters:
    naming-strategy: SNAKE_CASE

logging:
  level:
    org.zalando.logbook: TRACE
    
otp:
  expiration-minutes: 5
  max-attempts: 3
  code-length: 6
